### ISSUE TITLE
关于ebook-convert的安装问题

### ISSUE THREAD

**Issue by lidongye** [szyuema/setgitbook#1]
我的操作系统是CentOS 7
尝试安装calibre-ebook发生错误`ImportError: cannot import name QWebView`
在网上找到你的博客，尝试通过`npm install ebook-convert -g`安装，但gitbook依然无法找到这个ebook-convert，请问你可以给我一点帮助么？

**Comment by szyuema** [comment]
转换成pdf那个文档里面有讲这一块，应该是被墙了，没有安装成功

**Comment by lidongye** [comment]
`ebook-convert`已经安装成功了 npm list可以看到但是gitbook找不到  
我已经通过重新编译安装python2版本的PyQt5成功运行gitbook了
